### ISSUE TITLE
Credentials are sealed when application is sent to background

### ISSUE THREAD

**Issue by ptzianos** [ptzianos/hermes#3]
The `HermesLifecycleObserver` class is unnecessarily sealing the credentials when the application is not in the foreground even though the service that broadcasts data keeps running in the background.

**Comment by ptzianos** [comment]
Should be fixed in https://github.com/ptzianos/hermes/commit/3f417b3906b70540205dabd160579fc6fd1c6bfe

**Comment by ntsiam** [comment]
I confirm that the application now doesn't seal the credentials when it is not in the foreground!
