### ISSUE TITLE
Hermes service not streaming data

### ISSUE THREAD

**Issue by ntsiam** [ptzianos/hermes#7]
Hermes seems to be getting new samples from my other sensor application, which is registered normally, but it doesn't attempt to stream the data to tangle. I've attached a screenshot from Logcat reference.
![log_hermes](https://user-images.githubusercontent.com/15196806/60086808-11901d00-973c-11e9-8575-de46ea02c672.png)

**Comment by ptzianos** [comment]
This should have been fixed
