### ISSUE TITLE
App crashes on setup

### ISSUE THREAD

**Issue by ntsiam** [ptzianos/hermes#8]
![hermes_crush](https://user-images.githubusercontent.com/15196806/60179354-cf3f0c80-981d-11e9-96b3-b0cf4fbad523.png)

**Comment by ptzianos** [comment]
When you tried to log in, it was the first run after pulling the latest changes?

**Comment by ntsiam** [comment]
Yes

**Comment by ptzianos** [comment]
Probably this was due to the fact that the way the credentials where stored in the application changed and the application did not detect that the string was empty. I will add another check in the `unseal` method to make the checks stricter

**Comment by ptzianos** [comment]
Found the issue. It's fixed in 9627817
